
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/jvstein/pre-commit-dotnet-format
    rev: v0.2
    hooks:
    -   id: dotnet-format
