# SPDX-FileCopyrightText: 2021-2022 The Video Lister Contributors
#
# SPDX-License-Identifier: CC0-1.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
      - id: name-tests-test
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  #    - repo: https://github.com/dotnet/format
  #      rev: v5.1.225507
  #      hooks:
  #        - id: dotnet-format
  #          args: [dotNET]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: tests/
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        args: [-i, -a, -a]
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.931"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --strict]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: tests/
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --expand-star-imports,
            --remove-duplicate-keys,
            --remove-unused-variables,
          ]
  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.14.0
    hooks:
      - id: reuse
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
